### ISSUE TITLE
checksum mismatch

### ISSUE THREAD

**Issue by sahil2897** [udger/udger-updater-linux#9]
I am trying to update this database. But after downloading the database checksum mismatch is happening. I have tried it multiple times. Not sure what is the reason.

**Comment by mallat** [comment]
Hi.
It has been working without problems for several years.
What "**which sha1sum**" writes to you ... it should be something like this: "**/usr/bin/sha1sum**"

**Comment by sahil2897** [comment]
yeah. it is running fine. I was running it with /bin/sh . That's why it was giving error. with bash it works fine. Sorry, my bad. 
Thank you.
